### ISSUE TITLE
don't distinguish between uppercase and lowercase

### ISSUE THREAD

**Issue by ryosukes** [mochizukikotaro/octojump#18]
When I filter repositry,  I want to do not distinguish between uppercase and lowercase🙂

**Comment by mochizukikotaro** [comment]
@ryosukes Thanks! I agree with you. 👍

**Comment by ryosukes** [comment]
@mochizukikotaro thanks! I'll do it😀

**Comment by mochizukikotaro** [comment]
@ryosukes v0.1.9 is released! 👏
https://chrome.google.com/webstore/detail/octojump/ipddbipniemmmklkjabimbmnaejmnngn?hl=ja
Thnaks!
